const STORAGE_KEY='plano-estudos-v1';
const initialCourses=[
  {id:'fiap',name:'Big Data to Analytics',color:'#ed1c24',platform:'fiap',order:1},
  {id:'challenge',name:'Tech Challenge',color:'#f05a62',platform:'fiap',order:2},
  {id:'python',name:'Formação em Python',color:'#20639b',platform:'etek',order:1,status:'current'},
  {id:'ia',name:'Trilha de Inteligência Artificial',color:'#7c5ce5',platform:'etek',order:2,status:'planned'},
  {id:'powerbi',name:'Trilha de Power BI',color:'#f6a623',platform:'etek',order:3,status:'planned'},
  {id:'automacao',name:'Trilha de Automação',color:'#3caea3',platform:'etek',order:4,status:'planned'}
];
const initialDeadlines=[{id:'fiap-tech-challenge-2026-09',title:'Entrega do Tech Challenge',date:'2026-09-15',platform:'fiap',note:'Conferir solução, documentação e apresentação',done:false}];
const pythonStudyDates=['2026-07-13','2026-07-14','2026-07-15','2026-07-16','2026-07-17','2026-07-21','2026-07-23','2026-07-28','2026-07-30','2026-08-04','2026-08-06','2026-08-11','2026-08-13','2026-08-18','2026-08-20','2026-08-25','2026-08-27','2026-09-01','2026-09-03','2026-09-08','2026-09-10'];
const pythonCurriculum=[
['Boas-vindas e Introdução à Formação em Python','Introdução a Formação em Python','01:32'],
['Boas-vindas e Introdução à Formação em Python','Porque aprender Python se sei Power BI?','06:35'],
['Boas-vindas e Introdução à Formação em Python','Aplicações de Python para analista de dados e negócios','06:03'],
['Fundamentos','Seu Professor e Introdução ao Módulo','02:37'],
['Fundamentos','Instalando o Python','03:40'],
['Fundamentos','IDE de desenvolvimento nativo do Python (IDLE)','04:38'],
['Fundamentos','Instalando o VSCode','04:48'],
['Fundamentos','Configuração do VSCode (Extensões)','04:54'],
['Fundamentos','Configuração do VSCode (Terminal, scripts e pastas)','06:00'],
['Fundamentos','Configuração do VSCode (Tecla de Atalho)','03:49'],
['Fundamentos','IDEs de desenvolvimento - VSCode','06:06'],
['Fundamentos','IDEs de desenvolvimento - VSCode com Jupyter','07:55'],
['Fundamentos','IDEs de desenvolvimento - Google Colab','03:46'],
['Fundamentos','Comentários e Docstring','08:25'],
['Fundamentos','Como apagar os resultados do terminal - Método 1','07:16'],
['Fundamentos','Como apagar os resultados do terminal - Método 2','04:58'],
['Fundamentos','Boas práticas no Python - Parte 1','07:34'],
['Fundamentos','Boas práticas no Python - Parte 2','05:39'],
['Fundamentos','Resumo - Boas práticas no Python','atividade'],
['Fundamentos','Instrução Print - Parte 1','08:37'],
['Fundamentos','Instrução Print - Parte 2','12:41'],
['Fundamentos','Variáveis - Como utilizá-las em seus scripts - Parte 1','08:33'],
['Fundamentos','Variáveis - Como utilizá-las em seus scripts - Parte 2','05:46'],
['Fundamentos','Operadores Matemáticos - Parte 1','09:43'],
['Fundamentos','Operadores Matemáticos - Parte 2','06:06'],
['Fundamentos','Operadores Incrementais','05:03'],
['Fundamentos','Métodos nativos para Strings - Parte 1','15:28'],
['Fundamentos','Métodos nativos para Strings - Parte 2','09:18'],
['Fundamentos','Métodos nativos para Strings - Parte 3','07:38'],
['Fundamentos','Função INPUT e método FORMAT para strings','12:49'],
['Fundamentos','Operadores Relacionais','07:53'],
['Fundamentos','Operadores de associação','09:04'],
['Fundamentos','Operadores Lógicos','07:22'],
['Fundamentos','Variáveis e seu escopo de aplicação','08:03'],
['Fundamentos','Função range','06:16'],
['Fundamentos','Listas - Parte 1','07:42'],
['Fundamentos','Listas - Parte 2','10:45'],
['Fundamentos','Tuplas','05:43'],
['Fundamentos','Dicionários','07:03'],
['Fundamentos','Estrutura de Decisão IF','09:16'],
['Fundamentos','Estrutura de Repetição FOR','11:29'],
['Fundamentos','Estrutura de Repetição WHILE','12:25'],
['Fundamentos','Tratamento de Erros nos Scripts','12:08'],
['Fundamentos','Aprenda com IA - ChatGPT','06:01'],
['Fundamentos','Aprenda com IA - Copilot','06:06'],
['Fundamentos','GitHub Copilot - IA para gerar códigos','15:09'],
['Fundamentos','Finalização do módulo','00:42'],
['Análise de Dados','Apresentação do Módulo','01:14'],
['Análise de Dados','Biblioteca math - Aula 1','13:12'],
['Análise de Dados','Biblioteca math - Aula 2','11:36'],
['Análise de Dados','Biblioteca random - Aula 1','11:53'],
['Análise de Dados','Biblioteca random - Aula 2','11:30'],
['Análise de Dados','Biblioteca time','16:13'],
['Análise de Dados','Biblioteca datetime - Aula 1','12:29'],
['Análise de Dados','Biblioteca datetime - Aula 2','12:30'],
['Análise de Dados','Biblioteca os - Aula 1','12:31'],
['Análise de Dados','Biblioteca os - Aula 2','09:31'],
['Análise de Dados','Biblioteca faker - Aula 1','12:00'],
['Análise de Dados','Biblioteca faker - Aula 2 - Parte 1','13:38'],
['Análise de Dados','Biblioteca faker - Aula 2 - Parte 2','08:54'],
['Análise de Dados','Biblioteca faker - Aula 3','14:32'],
['Análise de Dados','O uso dos dados gerados no Power BI','04:11'],
['Análise de Dados','Biblioteca num2words - Aula 1','12:45'],
['Análise de Dados','Biblioteca num2words - Aula 2','05:26'],
['Análise de Dados','Biblioteca numpy - Aula 1','10:51'],
['Análise de Dados','Biblioteca numpy - Aula 2','13:56'],
['Análise de Dados','Biblioteca numpy - Aula 3','16:38'],
['Análise de Dados','Biblioteca pandas - Aula 1 - Parte 1','09:15'],
['Análise de Dados','Biblioteca pandas - Aula 1 - Parte 2','07:49'],
['Análise de Dados','Biblioteca pandas - Aula 2','14:55'],
['Análise de Dados','Biblioteca pandas - Aula 3','11:18'],
['Análise de Dados','Biblioteca pandas - Aula 4','13:21'],
['Análise de Dados','Biblioteca pandas - Aula 5','06:03'],
['Análise de Dados','Biblioteca pandas - Aula 6','06:35'],
['Análise de Dados','Biblioteca pandas - Aula 7','08:11'],
['Análise de Dados','Biblioteca pandas - Aula 8','12:33'],
['Análise de Dados','Biblioteca pandas - Aula 9','10:31'],
['Análise de Dados','Biblioteca pandas - Aula 10','15:44'],
['Análise de Dados','Biblioteca pandas - Aula 11','20:01'],
['Análise de Dados','Biblioteca matplotlib - Aula 1','10:41'],
['Análise de Dados','Biblioteca matplotlib - Aula 2','04:32'],
['Análise de Dados','Finalização do curso','01:44'],
['Queremos te ouvir!','Compartilhe sua experiência.','atividade']
].map(([module,title,duration],index)=>({number:index+1,module,title,duration,seconds:duration==='atividade'?0:duration.split(':').reduce((m,s)=>m*60+Number(s),0)}));
function buildPythonPlan(){let index=0;const result=[];pythonStudyDates.forEach((date,dateIndex)=>{let lessons=[];const datesLeft=pythonStudyDates.length-dateIndex;if(dateIndex===0){lessons=pythonCurriculum.slice(0,8);index=8}else if(datesLeft===1){lessons=pythonCurriculum.slice(index);index=pythonCurriculum.length}else{const remaining=pythonCurriculum.slice(index),remainingSeconds=remaining.reduce((sum,l)=>sum+l.seconds,0),target=remainingSeconds/datesLeft;let seconds=0;while(index<pythonCurriculum.length&&(pythonCurriculum.length-index)>datesLeft-1){const next=pythonCurriculum[index];if(lessons.length&&seconds>=target*.9)break;if(lessons.length&&next.module!==lessons[0].module&&seconds>=target*.65)break;lessons.push(next);seconds+=next.seconds;index++}if(!lessons.length&&index<pythonCurriculum.length)lessons.push(pythonCurriculum[index++])}const seconds=lessons.reduce((sum,l)=>sum+l.seconds,0),modules=[...new Set(lessons.map(l=>l.module))],start=lessons[0]?.number||0,end=lessons.at(-1)?.number||start;result.push({id:`py-${date}`,date,courseId:'python',module:modules.join(' + '),title:`Aulas ${start}${end>start?` a ${end}`:''} — ${modules.join(' + ')}`,minutes:Math.max(1,Math.ceil(seconds/60)),lessons,source:'etek-python-v12',done:false,completedAt:null})});return result}
const pythonPlanSessions=buildPythonPlan();
const legacyPythonTitles=new Set(['Instalação do Python, VS Code e primeiros códigos','Print, variáveis e operadores','Strings, input e formatação','Listas, tuplas e dicionários','If, for e while','Exercício de revisão dos fundamentos','Operadores relacionais, lógicos e de associação','Escopo de variáveis e range','Listas — exercícios práticos','Tuplas e dicionários — prática','Estruturas de decisão if','Laços for e while','Tratamento de erros','Math, random e time','Datetime e os','Faker e num2words','NumPy — aulas 1 e 2','NumPy 3 e introdução ao Pandas','Pandas — aulas 1 a 4','Pandas — aulas 5 a 8','Pandas — aulas 9 a 11','Matplotlib e finalização do curso']);
const rows=[
['2026-07-20','fiap','Big Data','Aula 1 — Definição e os 5 Vs do Big Data',62,3682],['2026-07-22','fiap','Big Data','Aula 2 — Hadoop e Spark',73,4337],['2026-07-24','challenge','Revisão','Revisar Big Data e praticar estruturas',120],['2026-07-27','fiap','Big Data','Aula 3 — Armazenamento de dados na nuvem',140,8400],['2026-07-29','fiap','Big Data','Aula 4 — Manipulação de dados com Spark',74,4397],['2026-07-31','challenge','Planejamento','Registrar ideias e dúvidas do projeto',120],
['2026-08-03','fiap','Bancos de Dados','Aula 1 — Bancos relacionais',56,3322],['2026-08-05','fiap','Bancos de Dados','Aula 2 — Modelo Entidade-Relacionamento',23,1355],['2026-08-07','challenge','Pesquisa','Relacionar o conteúdo ao desafio',120],['2026-08-10','fiap','Bancos de Dados','Aula 3 — DW, Data Lake, Lakehouse, Mesh e Fabric',78,4676],['2026-08-12','fiap','Bancos de Dados','Aula 4 — SQL, filtros, agrupamentos e joins',85,5056],['2026-08-14','challenge','Escopo','Definir tema, dados e entregáveis',120],['2026-08-17','fiap','Bancos de Dados','Aula 5 — Bancos NoSQL',87,5161],['2026-08-19','fiap','Storage','Aula 1 — Data Warehouse',111,6619],['2026-08-21','challenge','Arquitetura','Desenhar a solução e dividir tarefas',120],
['2026-08-24','fiap','Storage','Aula 2 — Data Lake',93,5537],['2026-08-26','fiap','Storage','Aula 3 — Data Lakehouse',22,1314],['2026-08-28','challenge','Implementação','Começar scripts e documentação',120],['2026-08-31','fiap','Revisão','Revisar Big Data e bancos de dados',90],['2026-09-02','fiap','Revisão','Revisar storage, Spark e Databricks',90],['2026-09-04','challenge','Implementação','Desenvolver e testar a solução',120],['2026-09-07','fiap','Revisão final','Consolidar conceitos e pendências',90],['2026-09-09','challenge','Finalização','Fechar documentação e apresentação',90],['2026-09-11','challenge','Revisão final','Revisar e deixar pronto para envio',120],['2026-09-14','challenge','Entrega','Conferência final e envio — prazo oficial 15/09',30]
];
const baseSessions=rows.map((r,i)=>({id:`s${i+1}`,date:r[0],courseId:r[1],module:r[2],title:r[3],minutes:r[4],...(r[5]?{durationSeconds:r[5],durationSource:'fiap-live-2026-07-20'}:{}),done:false,completedAt:null}));
const initialState={courses:initialCourses,sessions:[...pythonPlanSessions,...baseSessions],deadlines:initialDeadlines,theme:'light'};
let state=loadState();let weekOffset=0;const autoReplanCount=autoRescheduleOverdue(state);if(autoReplanCount)localStorage.setItem(STORAGE_KEY,JSON.stringify(state));let installPrompt=null;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function loadState(){try{return migrateState(JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(initialState))}catch{return migrateState(structuredClone(initialState))}}
function syncPythonPlan(saved){const current=saved.sessions.filter(s=>s.courseId==='python'),generated=current.filter(s=>s.source==='etek-python-v12'),legacy=current.filter(s=>legacyPythonTitles.has(s.title)),custom=current.filter(s=>s.source!=='etek-python-v12'&&!legacyPythonTitles.has(s.title)),previous=[...generated,...legacy],planned=pythonPlanSessions.map(plan=>{const old=previous.find(s=>s.id===plan.id)||previous.find(s=>s.date===plan.date);return{...structuredClone(plan),done:!!old?.done,completedAt:old?.completedAt||null,...(old?.rescheduled?{date:old.date,originalDate:old.originalDate||plan.date,rescheduled:true}:{}),...(old?.actualMinutes?{actualMinutes:old.actualMinutes}:{}),...(old?.note?{note:old.note}:{})}});saved.sessions=[...saved.sessions.filter(s=>s.courseId!=='python'),...custom,...planned]}
function syncFiapDurations(saved){baseSessions.filter(base=>base.durationSeconds).forEach(base=>{const current=saved.sessions.find(s=>s.courseId==='fiap'&&s.title===base.title);if(current){current.minutes=base.minutes;current.durationSeconds=base.durationSeconds;current.durationSource=base.durationSource}else saved.sessions.push(structuredClone(base))})}
function migrateState(saved){saved.courses=saved.courses||[];initialCourses.forEach(base=>{const found=saved.courses.find(c=>c.id===base.id);if(found)Object.assign(found,base);else saved.courses.push({...base})});saved.sessions=saved.sessions||[];saved.deadlines=saved.deadlines||[];initialDeadlines.forEach(base=>{if(!saved.deadlines.some(d=>d.id===base.id))saved.deadlines.push(structuredClone(base))});saved.theme=saved.theme||'light';syncPythonPlan(saved);syncFiapDurations(saved);moveWeekends(saved.sessions);return saved}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}
function course(id){return state.courses.find(c=>c.id===id)||{name:'Outro',color:'#7c5ce5'}}
function fmtMinutes(m){const h=Math.floor(m/60),min=m%60;return h?`${h}h${min?` ${min}min`:''}`:`${min}min`}
function sessionSeconds(s){return s.durationSeconds||s.minutes*60}
function fmtSeconds(total){const h=Math.floor(total/3600),min=Math.floor(total%3600/60),sec=total%60;return `${h?`${h}h `:''}${min?`${String(min).padStart(h?2:1,'0')}min `:''}${sec?`${String(sec).padStart(h||min?2:1,'0')}s`:''}`.trim()||'0min'}
function sessionDuration(s){return s.durationSeconds?fmtSeconds(s.durationSeconds):fmtMinutes(s.minutes)}
function localDate(s){return new Date(`${s}T12:00:00`)}
function isoDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function nextWeekday(date){const d=localDate(date);while([0,6].includes(d.getDay()))d.setDate(d.getDate()+1);return isoDate(d)}
function moveWeekends(sessions){let moved=0;sessions.filter(s=>!s.done).forEach(s=>{const safe=nextWeekday(s.date);if(safe!==s.date){s.date=safe;moved++}});return moved}
function addDays(date,days){const d=new Date(date);d.setDate(d.getDate()+days);return d}
function mondayOf(date){const d=new Date(date),distance=(d.getDay()+6)%7;d.setDate(d.getDate()-distance);d.setHours(12,0,0,0);return d}
function autoRescheduleOverdue(saved){const today=isoDate(new Date()),overdue=saved.sessions.filter(s=>!s.done&&s.date<today);if(!overdue.length)return 0;const platformOf=s=>saved.courses.find(c=>c.id===s.courseId)?.platform||'other',loads=new Map(),fiapDates=new Set();saved.sessions.filter(s=>!s.done&&s.date>=today).forEach(s=>{loads.set(s.date,(loads.get(s.date)||0)+s.minutes);if(platformOf(s)==='fiap')fiapDates.add(s.date)});overdue.sort((a,b)=>a.date.localeCompare(b.date)||(platformOf(a)==='fiap'?-1:1));let moved=0;overdue.forEach(s=>{const platform=platformOf(s),limit=Math.max(platform==='fiap'?180:90,s.minutes);let candidate=localDate(nextWeekday(today));for(let tries=0;tries<365;tries++){if([0,6].includes(candidate.getDay())){candidate.setDate(candidate.getDate()+1);continue}const date=isoDate(candidate),load=loads.get(date)||0,allowed=load+s.minutes<=limit&&(platform==='fiap'||!fiapDates.has(date));if(allowed){s.originalDate=s.originalDate||s.date;s.date=date;s.rescheduled=true;loads.set(date,load+s.minutes);if(platform==='fiap')fiapDates.add(date);moved++;break}candidate.setDate(candidate.getDate()+1)}});if(moved)saved.lastAutoReschedule={date:today,count:moved};return moved}
function priority(s){return course(s.courseId).platform==='fiap'?0:1}
function byPriority(a,b){return a.date.localeCompare(b.date)||priority(a)-priority(b)||a.title.localeCompare(b.title)}
function parseDuration(value){const text=String(value).trim();if(/^\d+$/.test(text))return Number(text);if(/^\d{1,3}:\d{2}$/.test(text)){const [m,s]=text.split(':').map(Number);if(s<60)return Math.max(1,Math.ceil((m*60+s)/60))}return 0}
function dateParts(s){const d=localDate(s);return{day:d.getDate(),month:d.toLocaleDateString('pt-BR',{month:'short'}).replace('.',''),full:d.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}}
function sessionLessonItems(s){if(Array.isArray(s.lessons))return s.lessons.map((lesson,i)=>typeof lesson==='string'?{number:i+1,title:lesson,duration:''}:lesson);return s.courseId==='python'?[{number:1,title:s.title,duration:''}]:[]}
function sessionLessons(s){return sessionLessonItems(s).map(lesson=>lesson.title)}
function lessonList(s){const lessons=sessionLessonItems(s);return lessons.length?`<div class="lesson-list">${lessons.map(lesson=>`<div class="lesson-item"><b>Conteúdo ${lesson.number}</b><span class="lesson-name">${escapeHtml(lesson.title)}</span><span class="lesson-duration">${escapeHtml(lesson.duration||'')}</span></div>`).join('')}</div>`:''}
function sessionCard(s){const c=course(s.courseId),d=dateParts(s.date),fiap=c.platform==='fiap',platform=c.platform==='etek'?'ETEK':fiap?'FIAP':'OUTRA',lessons=sessionLessonItems(s);return `<article class="session-card ${s.done?'done':''} ${fiap?'fiap-priority':''}" style="--course-color:${c.color}"><div class="date-box"><strong>${d.day}</strong><span>${d.month}</span></div><div><h3>${escapeHtml(s.title)} ${fiap?'<span class="priority-tag">PRIORIDADE</span>':''}${s.rescheduled?'<span class="rescheduled-tag">REPLANEJADO</span>':''}</h3><div class="meta"><span class="platform-badge platform-${c.platform||'other'}">${platform}</span><span class="pill">${escapeHtml(c.name)}</span><span>${escapeHtml(s.module)}</span><span>${lessons.length?`${lessons.length} ${lessons.length===1?'conteúdo':'conteúdos'} • `:''}${sessionDuration(s)}</span>${s.durationSource?'<span class="pill">Duração real FIAP</span>':''}${s.actualMinutes?`<span>Realizado: ${fmtMinutes(s.actualMinutes)}</span>`:''}</div>${lessonList(s)}</div><input class="check" type="checkbox" aria-label="Marcar ${escapeHtml(s.title)} como concluído" data-session-id="${s.id}" ${s.done?'checked':''}></article>`}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function render(){document.documentElement.classList.toggle('dark',state.theme==='dark');$('#themeBtn').textContent=state.theme==='dark'?'☀':'☾';const total=state.sessions.reduce((a,s)=>a+sessionSeconds(s),0),done=state.sessions.filter(s=>s.done).reduce((a,s)=>a+sessionSeconds(s),0),pct=total?Math.round(done/total*100):0;$('#totalHours').textContent=fmtSeconds(total);$('#doneHours').textContent=fmtSeconds(done);$('#remainingCount').textContent=state.sessions.filter(s=>!s.done).length;$('#progressPercent').textContent=`${pct}%`;$('#progressRing').style.strokeDashoffset=308-(308*pct/100);$('#streak').textContent=`${calcStreak()} dias úteis`;const now=new Date(),today=isoDate(now),report=state.lastAutoReschedule,showReplan=report?.date===today&&report.count>0;$('#todayLabel').textContent=now.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});$('#weekendNotice').hidden=![0,6].includes(now.getDay());$('#replanNotice').hidden=!showReplan;if(showReplan)$('#replanText').textContent=`${report.count} ${report.count===1?'sessão atrasada foi movida':'sessões atrasadas foram movidas'} para os próximos dias úteis, mantendo a FIAP em primeiro lugar.`;const next=state.sessions.filter(s=>!s.done).sort(byPriority).slice(0,5);$('#heroTitle').textContent=next[0]?`Próximo: ${next[0].title}`:'Plano concluído!';$('#heroSubtitle').textContent=next[0]?`${dateParts(next[0].date).full} • ${sessionDuration(next[0])}`:'Você concluiu todas as sessões.';$('#nextSessions').innerHTML=next.length?next.map(sessionCard).join(''):'<div class="empty">Nenhuma sessão pendente. Que conquista!</div>';renderTodayOverview(now);renderDeadlines();renderWeek();renderPlan();renderCourses();fillCourseOptions();fillStudyOptions();bindChecks();bindDeadlineChecks()}
function renderTodayOverview(now){const today=isoDate(now),sessions=state.sessions.filter(s=>!s.done&&s.date===today).sort(byPriority),seconds=sessions.reduce((a,s)=>a+sessionSeconds(s),0),activities=sessions.reduce((n,s)=>n+(sessionLessonItems(s).length||1),0),weekend=[0,6].includes(now.getDay());$('#todayPlan').textContent=weekend?'Descanso':activities?`${activities} ${activities===1?'conteúdo':'conteúdos'}`:'Agenda livre';$('#todayDetail').textContent=weekend?'Sábado e domingo são seus':sessions.length?sessions.map(s=>course(s.courseId).name).filter((v,i,a)=>a.indexOf(v)===i).join(' + '):'Nenhum estudo pendente para hoje';$('#todayMinutes').textContent=fmtSeconds(seconds);if(seconds){const finish=new Date(now.getTime()+seconds*1000);$('#finishTime').textContent=finish.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});$('#finishDetail').textContent=`considerando início às ${now.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`}else{$('#finishTime').textContent='—';$('#finishDetail').textContent=weekend?'Aproveite seu descanso':'Sem estudos pendentes'}const fiap=sessions.find(s=>course(s.courseId).platform==='fiap');$('#todayFocus').textContent=fiap?'FIAP':sessions.length?course(sessions[0].courseId).name:'FIAP'}
function deadlineCountdown(date){const days=Math.round((localDate(date)-localDate(isoDate(new Date())))/86400000);if(days<0)return{days,label:`Atrasado há ${Math.abs(days)} ${Math.abs(days)===1?'dia':'dias'}`,level:'urgent'};if(days===0)return{days,label:'Vence hoje',level:'urgent'};if(days===1)return{days,label:'Vence amanhã',level:'urgent'};return{days,label:`Faltam ${days} dias`,level:days<=7?'urgent':days<=30?'attention':'calm'}}
function renderDeadlines(){const list=state.deadlines.filter(d=>!d.done).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,3);$('#deadlineList').innerHTML=list.length?list.map(d=>{const count=deadlineCountdown(d.date),platform=d.platform==='etek'?'ETEK':'FIAP';return `<article class="deadline-card deadline-${count.level}"><div class="deadline-date"><strong>${localDate(d.date).getDate()}</strong><span>${localDate(d.date).toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}</span></div><div class="deadline-copy"><div><span class="platform-badge platform-${d.platform}">${platform}</span><span class="deadline-countdown">${count.label}</span></div><h4>${escapeHtml(d.title)}</h4>${d.note?`<p>${escapeHtml(d.note)}</p>`:''}</div><input class="deadline-check" type="checkbox" aria-label="Marcar o prazo ${escapeHtml(d.title)} como concluído" data-deadline-id="${d.id}"></article>`}).join(''):'<div class="deadline-empty">Todos os prazos foram concluídos 🎉</div>'}
function workload(minutes){if(!minutes)return{label:'Livre',className:'free'};if(minutes<=45)return{label:'Leve',className:'light'};if(minutes<=90)return{label:'Equilibrada',className:'balanced'};return{label:'Intensa',className:'intense'}}
function renderWeek(){const monday=addDays(mondayOf(new Date()),weekOffset*7),days=Array.from({length:5},(_,i)=>addDays(monday,i)),start=isoDate(days[0]),end=isoDate(days[4]),all=state.sessions.filter(s=>s.date>=start&&s.date<=end).sort(byPriority),pending=all.filter(s=>!s.done),total=pending.reduce((sum,s)=>sum+s.minutes,0),fiap=pending.filter(s=>course(s.courseId).platform==='fiap').reduce((sum,s)=>sum+s.minutes,0),etek=pending.filter(s=>course(s.courseId).platform==='etek').reduce((sum,s)=>sum+s.minutes,0),today=isoDate(new Date());$('#weekRange').textContent=`${days[0].toLocaleDateString('pt-BR',{day:'2-digit',month:'long'})} a ${days[4].toLocaleDateString('pt-BR',{day:'2-digit',month:'long',year:'numeric'})}`;$('#weekSummary').innerHTML=`<article><span>Carga pendente</span><strong>${fmtMinutes(total)}</strong></article><article class="fiap-summary"><span>FIAP</span><strong>${fmtMinutes(fiap)}</strong></article><article class="etek-summary"><span>ETEK</span><strong>${fmtMinutes(etek)}</strong></article><article><span>Dias com estudo</span><strong>${new Set(pending.map(s=>s.date)).size} de 5</strong></article>`;$('#weekGrid').innerHTML=days.map(day=>{const date=isoDate(day),sessions=all.filter(s=>s.date===date),minutes=sessions.filter(s=>!s.done).reduce((sum,s)=>sum+s.minutes,0),load=workload(minutes),dayName=day.toLocaleDateString('pt-BR',{weekday:'long'}),platformLabel=c=>c.platform==='fiap'?'FIAP':c.platform==='etek'?'ETEK':'OUTRA';return `<article class="week-day ${date===today?'today-day':''}"><header><div><span>${dayName}</span><strong>${day.getDate()}</strong></div><span class="load-tag load-${load.className}">${load.label}</span></header><div class="week-day-total">${minutes?`${fmtMinutes(minutes)} pendentes`:'Sem pendências'}</div><div class="week-sessions">${sessions.length?sessions.map(s=>{const c=course(s.courseId);return `<div class="week-session ${s.done?'done':''}"><div><span class="platform-badge platform-${c.platform||'other'}">${platformLabel(c)}</span>${s.rescheduled?'<span class="tiny-replan">REPLANEJADO</span>':''}</div><strong>${escapeHtml(s.title)}</strong><small>${escapeHtml(c.name)} • ${fmtMinutes(s.minutes)}</small></div>`}).join(''):'<div class="week-free">Dia livre para respirar 🌿</div>'}</div></article>`}).join('')}
function renderPlan(){const platform=$('#platformFilter').value||'all',track=$('#trackFilter').value||'all',status=$('#statusFilter').value||'all';const list=state.sessions.filter(s=>{const c=course(s.courseId);return(platform==='all'||c.platform===platform)&&(track==='all'||s.courseId===track)&&(status==='all'||(status==='done'&&s.done)||(status==='pending'&&!s.done))}).sort(byPriority);let month='';$('#allSessions').innerHTML=list.map(s=>{const m=localDate(s.date).toLocaleDateString('pt-BR',{month:'long',year:'numeric'});const head=m!==month?`<div class="timeline-month">${month=m}</div>`:'';return head+sessionCard(s)}).join('')||'<div class="empty">Nenhuma sessão encontrada para esses filtros.</div>';bindChecks()}
function courseMetrics(c){const ss=state.sessions.filter(s=>s.courseId===c.id),done=ss.filter(s=>s.done).length,lessonCount=ss.reduce((n,s)=>n+sessionLessonItems(s).length,0),doneLessons=ss.filter(s=>s.done).reduce((n,s)=>n+sessionLessonItems(s).length,0),p=lessonCount?Math.round(doneLessons/lessonCount*100):ss.length?Math.round(done/ss.length*100):0;return{ss,done,p,lessonCount,doneLessons,minutes:ss.reduce((a,s)=>a+s.minutes,0),seconds:ss.reduce((a,s)=>a+sessionSeconds(s),0)}}
function compactCourse(c){const m=courseMetrics(c);return `<article class="mini-course" style="--course-color:${c.color}"><div><span class="mini-dot"></span><h4>${escapeHtml(c.name)}</h4><p>${m.ss.length} sessões • ${fmtSeconds(m.seconds)}</p></div><strong>${m.p}%</strong><div class="mini-progress"><span style="width:${m.p}%"></span></div></article>`}
function pythonGuide(){const upcoming=state.sessions.filter(s=>s.courseId==='python'&&!s.done).sort(byPriority).slice(0,4);if(!upcoming.length)return '<div class="python-guide complete-guide"><strong>Python concluído!</strong><span>Você terminou todos os conteúdos planejados.</span></div>';return `<div class="python-guide"><div class="guide-title"><strong>Seus próximos conteúdos</strong><span>Grade oficial da ETEK</span></div>${upcoming.map(s=>{const d=dateParts(s.date),lessons=sessionLessonItems(s);return `<div class="python-day"><div class="python-day-date"><strong>${d.full}</strong><span>${lessons.length} ${lessons.length===1?'conteúdo':'conteúdos'} • ${fmtMinutes(s.minutes)}</span></div><div class="python-lessons">${lessons.map(lesson=>`<div class="python-lesson"><b>${lesson.number}</b><span>${escapeHtml(lesson.title)}</span><small>${escapeHtml(lesson.duration||'')}</small></div>`).join('')}</div></div>`}).join('')}<div class="weekend-free">☕ Python às terças e quintas • FIAP tem prioridade • fins de semana livres</div></div>`}
function renderCourses(){
  const fiap=state.courses.filter(c=>c.platform==='fiap').sort((a,b)=>a.order-b.order);
  $('#fiapCourses').innerHTML=fiap.map(compactCourse).join('');
  const etek=state.courses.filter(c=>c.platform==='etek').sort((a,b)=>a.order-b.order);
  $('#etekRoadmap').innerHTML=etek.map((c,i)=>{const m=courseMetrics(c),active=c.status==='current',complete=m.p===100&&m.ss.length>0;return `<article class="roadmap-step ${active?'active':''} ${complete?'complete':''}" style="--course-color:${c.color}"><div class="step-number">${complete?'✓':i+1}</div><div class="step-copy"><span>${active?'EM ANDAMENTO':complete?'CONCLUÍDA':'PRÓXIMA ETAPA'}</span><h4>${escapeHtml(c.name)}</h4><p>${m.ss.length?`${c.id==='python'?`${m.lessonCount} conteúdos oficiais`:`${m.ss.length} sessões planejadas`} • ${m.p}% concluído`:'Será planejada quando você iniciar esta trilha.'}</p>${m.ss.length?`<div class="mini-progress"><span style="width:${m.p}%"></span></div>`:''}${c.id==='python'&&active?pythonGuide():''}</div></article>`}).join('');
  const others=state.courses.filter(c=>!c.platform||c.platform==='other');
  $('.other-courses').hidden=!others.length;
  $('#courseGrid').innerHTML=others.map(c=>{const m=courseMetrics(c);return `<article class="course-card" style="--course-color:${c.color}"><h3>${escapeHtml(c.name)}</h3><p class="meta">${m.ss.length} sessões • ${fmtMinutes(m.minutes)}</p><div class="course-progress"><span style="width:${m.p}%"></span></div><footer><span>${m.done} concluídas</span><strong>${m.p}%</strong></footer></article>`}).join('');
}
function fillCourseOptions(){const opts=state.courses.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('');$('#sessionCourse').innerHTML=opts;const current=$('#trackFilter').value;$('#trackFilter').innerHTML='<option value="all">Todos os cursos</option>'+opts;if([...$('#trackFilter').options].some(o=>o.value===current))$('#trackFilter').value=current}
function fillStudyOptions(){const pending=state.sessions.filter(s=>!s.done).sort(byPriority).slice(0,20);$('#studySession').innerHTML=pending.map(s=>`<option value="${s.id}">${escapeHtml(dateParts(s.date).full)} — ${escapeHtml(s.title)}</option>`).join('')||'<option value="">Nenhuma sessão pendente</option>'}
function bindChecks(){$$('.check').forEach(el=>el.onchange=()=>{const s=state.sessions.find(x=>x.id===el.dataset.sessionId);s.done=el.checked;s.completedAt=el.checked?new Date().toISOString():null;save();toast(el.checked?'Sessão concluída!':'Sessão reaberta')})}
function bindDeadlineChecks(){$$('.deadline-check').forEach(el=>el.onchange=()=>{const d=state.deadlines.find(x=>x.id===el.dataset.deadlineId);if(!d)return;d.done=el.checked;d.completedAt=el.checked?new Date().toISOString():null;save();toast('Prazo concluído!')})}
function businessDaysBetween(a,b){let count=0,d=new Date(b);while(d<a){d.setDate(d.getDate()+1);if(![0,6].includes(d.getDay()))count++}return count}
function calcStreak(){const days=[...new Set(state.sessions.filter(s=>s.done&&s.completedAt).map(s=>s.completedAt.slice(0,10)))].sort().reverse();if(!days.length)return 0;let streak=1;for(let i=1;i<days.length;i++){const a=localDate(days[i-1]),b=localDate(days[i]);if(businessDaysBetween(a,b)===1)streak++;else break}return streak}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.view}View`).classList.add('active')});
$('#prevWeek').onclick=()=>{weekOffset--;renderWeek()};$('#nextWeek').onclick=()=>{weekOffset++;renderWeek()};$('#currentWeek').onclick=()=>{weekOffset=0;renderWeek()};
$$('[data-open-modal]').forEach(b=>b.onclick=()=>{$(`#${b.dataset.openModal}Modal`).showModal()});$$('.close-modal').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#sessionForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),minutes=parseDuration(f.get('duration')),date=f.get('date');if(!minutes){toast('Informe a duração como 28:23 ou 60');return}if([0,6].includes(localDate(date).getDay())){toast('Escolha um dia útil para preservar seu descanso');return}state.sessions.push({id:`s${Date.now()}`,date,courseId:f.get('course'),module:f.get('module'),title:f.get('title'),minutes,done:false,completedAt:null});save();e.target.reset();$('#sessionModal').close();toast('Sessão adicionada em um dia útil')};
$('#studyForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),s=state.sessions.find(x=>x.id===f.get('session'));if(!s){toast('Nenhuma sessão selecionada');return}s.done=true;s.completedAt=new Date().toISOString();s.actualMinutes=Number(f.get('actualMinutes'));s.note=String(f.get('note')||'').trim();save();e.target.reset();$('#studyModal').close();toast('Estudo de hoje registrado!')};
$('#courseForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),name=f.get('name');state.courses.push({id:`c${Date.now()}`,name,color:f.get('color'),platform:'other'});save();e.target.reset();$('#courseModal').close();toast('Curso criado')};
$('#deadlineForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.deadlines.push({id:`d${Date.now()}`,title:String(f.get('title')).trim(),date:f.get('date'),platform:f.get('platform'),note:String(f.get('note')||'').trim(),done:false});save();e.target.reset();$('#deadlineModal').close();toast('Prazo adicionado')};
$('#platformFilter').onchange=renderPlan;$('#trackFilter').onchange=renderPlan;$('#statusFilter').onchange=renderPlan;$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save()};
$('#weekdayBtn').onclick=()=>{const weekends=moveWeekends(state.sessions),overdue=autoRescheduleOverdue(state),moved=weekends+overdue;save();toast(moved?`${moved} ${moved===1?'sessão reorganizada':'sessões reorganizadas'}`:'Seu cronograma já está em dia')};
function icsDate(date,time){return `${date.replaceAll('-','')}T${time.replace(':','')}00`}
function icsEscape(v){return String(v).replaceAll('\\','\\\\').replaceAll(',','\\,').replaceAll(';','\\;').replaceAll('\n','\\n')}
$('#calendarBtn').onclick=()=>{const pending=state.sessions.filter(s=>!s.done).sort(byPriority),lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Horizonte//Plano de Estudos//PT-BR','CALSCALE:GREGORIAN'];pending.forEach(s=>{const start='19:00',end=new Date(localDate(s.date));end.setHours(19,0,0,0);end.setMinutes(end.getMinutes()+s.minutes);const endTime=`${String(end.getHours()).padStart(2,'0')}:${String(end.getMinutes()).padStart(2,'0')}`,c=course(s.courseId),isFiap=c.platform==='fiap';lines.push('BEGIN:VEVENT',`UID:${s.id}@horizonte`, `DTSTART;TZID=America/Sao_Paulo:${icsDate(s.date,start)}`,`DTEND;TZID=America/Sao_Paulo:${icsDate(s.date,endTime)}`,`SUMMARY:${icsEscape(isFiap?'🎓 FIAP — '+s.title:'📘 '+s.title)}`,`DESCRIPTION:${icsEscape(`${c.name} • ${s.module}${isFiap?' • Prioridade FIAP':''}`)}`,'END:VEVENT')});lines.push('END:VCALENDAR');const blob=new Blob([lines.join('\r\n')],{type:'text/calendar'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='horizonte-google-agenda.ics';a.click();URL.revokeObjectURL(a.href);toast('Arquivo da agenda criado')};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`plano-estudos-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!data.courses||!data.sessions)throw 0;state=migrateState(data);save();toast('Backup restaurado')}catch{toast('Arquivo de backup inválido')}};
$('#resetBtn').onclick=()=>{if(confirm('Restaurar o plano inicial e apagar alterações?')){state=structuredClone(initialState);save();toast('Plano restaurado')}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').hidden=true}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
render();
