const STORAGE_KEY='plano-estudos-v1';
const initialCourses=[
  {id:'python',name:'Formação em Python',color:'#20639b'},
  {id:'fiap',name:'FIAP — Big Data',color:'#3caea3'},
  {id:'challenge',name:'Tech Challenge',color:'#f6a623'}
];
const rows=[
['2026-07-13','python','Preparação','Instalação do Python, VS Code e primeiros códigos',60],['2026-07-14','python','Fundamentos','Print, variáveis e operadores',60],['2026-07-15','python','Fundamentos','Strings, input e formatação',60],['2026-07-16','python','Estruturas','Listas, tuplas e dicionários',60],['2026-07-17','python','Lógica','If, for e while',60],['2026-07-18','python','Prática','Exercício de revisão dos fundamentos',60],
['2026-07-20','fiap','Big Data','Aula 1 — Definição e os 5 Vs do Big Data',90],['2026-07-21','python','Fundamentos','Operadores relacionais, lógicos e de associação',60],['2026-07-22','fiap','Big Data','Aula 2 — Hadoop e Spark',90],['2026-07-23','python','Fundamentos','Escopo de variáveis e range',60],['2026-07-25','challenge','Revisão','Revisar Big Data e praticar estruturas',120],['2026-07-27','fiap','Big Data','Aula 3 — Armazenamento de dados na nuvem',90],['2026-07-28','python','Estruturas','Listas — exercícios práticos',60],['2026-07-29','fiap','Big Data','Aula 4 — Manipulação de dados com Spark',90],['2026-07-30','python','Estruturas','Tuplas e dicionários — prática',60],['2026-08-01','challenge','Planejamento','Registrar ideias e dúvidas do projeto',120],
['2026-08-03','fiap','Bancos de Dados','Aula 1 — Bancos relacionais',90],['2026-08-04','python','Lógica','Estruturas de decisão if',60],['2026-08-05','fiap','Bancos de Dados','Aula 2 — Modelo Entidade-Relacionamento',90],['2026-08-06','python','Lógica','Laços for e while',60],['2026-08-08','challenge','Pesquisa','Relacionar o conteúdo ao desafio',120],['2026-08-10','fiap','Bancos de Dados','Aula 3 — DW, Data Lake, Lakehouse, Mesh e Fabric',90],['2026-08-11','python','Qualidade','Tratamento de erros',60],['2026-08-12','fiap','Bancos de Dados','Aula 4 — SQL, filtros, agrupamentos e joins',90],['2026-08-13','python','Bibliotecas','Math, random e time',60],['2026-08-15','challenge','Escopo','Definir tema, dados e entregáveis',120],['2026-08-17','fiap','Bancos de Dados','Aula 5 — Bancos NoSQL',90],['2026-08-18','python','Bibliotecas','Datetime e os',60],['2026-08-19','fiap','Storage','Aula 1 — Data Warehouse',90],['2026-08-20','python','Dados sintéticos','Faker e num2words',60],['2026-08-22','challenge','Arquitetura','Desenhar a solução e dividir tarefas',120],
['2026-08-24','fiap','Storage','Aula 2 — Data Lake',90],['2026-08-25','python','NumPy','NumPy — aulas 1 e 2',60],['2026-08-26','fiap','Storage','Aula 3 — Data Lakehouse',90],['2026-08-27','python','NumPy e Pandas','NumPy 3 e introdução ao Pandas',60],['2026-08-29','challenge','Implementação','Começar scripts e documentação',120],['2026-08-31','fiap','Revisão','Revisar Big Data e bancos de dados',90],['2026-09-01','python','Pandas','Pandas — aulas 1 a 4',60],['2026-09-02','fiap','Revisão','Revisar storage, Spark e Databricks',90],['2026-09-03','python','Pandas','Pandas — aulas 5 a 8',60],['2026-09-05','challenge','Implementação','Desenvolver e testar a solução',120],['2026-09-07','fiap','Revisão final','Consolidar conceitos e pendências',90],['2026-09-08','python','Pandas','Pandas — aulas 9 a 11',60],['2026-09-09','challenge','Finalização','Fechar documentação e apresentação',90],['2026-09-10','python','Visualização','Matplotlib e finalização do curso',60],['2026-09-12','challenge','Revisão final','Revisar e deixar pronto para envio',120],['2026-09-14','challenge','Entrega','Conferência final e envio — prazo oficial 15/09',30]
];
const initialState={courses:initialCourses,sessions:rows.map((r,i)=>({id:`s${i+1}`,date:r[0],courseId:r[1],module:r[2],title:r[3],minutes:r[4],done:false,completedAt:null})),theme:'light'};
let state=loadState();let installPrompt=null;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(initialState)}catch{return structuredClone(initialState)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}
function course(id){return state.courses.find(c=>c.id===id)||{name:'Outro',color:'#7c5ce5'}}
function fmtMinutes(m){const h=Math.floor(m/60),min=m%60;return h?`${h}h${min?` ${min}min`:''}`:`${min}min`}
function localDate(s){return new Date(`${s}T12:00:00`)}
function dateParts(s){const d=localDate(s);return{day:d.getDate(),month:d.toLocaleDateString('pt-BR',{month:'short'}).replace('.',''),full:d.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}}
function sessionCard(s){const c=course(s.courseId),d=dateParts(s.date);return `<article class="session-card ${s.done?'done':''}" style="--course-color:${c.color}"><div class="date-box"><strong>${d.day}</strong><span>${d.month}</span></div><div><h3>${escapeHtml(s.title)}</h3><div class="meta"><span class="pill">${escapeHtml(c.name)}</span><span>${escapeHtml(s.module)}</span><span>${fmtMinutes(s.minutes)}</span></div></div><input class="check" type="checkbox" aria-label="Marcar ${escapeHtml(s.title)} como concluído" data-session-id="${s.id}" ${s.done?'checked':''}></article>`}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function render(){document.documentElement.classList.toggle('dark',state.theme==='dark');$('#themeBtn').textContent=state.theme==='dark'?'☀':'☾';const total=state.sessions.reduce((a,s)=>a+s.minutes,0),done=state.sessions.filter(s=>s.done).reduce((a,s)=>a+s.minutes,0),pct=total?Math.round(done/total*100):0;$('#totalHours').textContent=fmtMinutes(total);$('#doneHours').textContent=fmtMinutes(done);$('#remainingCount').textContent=state.sessions.filter(s=>!s.done).length;$('#progressPercent').textContent=`${pct}%`;$('#progressRing').style.strokeDashoffset=308-(308*pct/100);$('#streak').textContent=`${calcStreak()} dias`;const now=new Date();$('#todayLabel').textContent=now.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});const next=state.sessions.filter(s=>!s.done).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5);$('#heroTitle').textContent=next[0]?`Próximo: ${next[0].title}`:'Plano concluído!';$('#heroSubtitle').textContent=next[0]?`${dateParts(next[0].date).full} • ${fmtMinutes(next[0].minutes)}`:'Você concluiu todas as sessões.';$('#nextSessions').innerHTML=next.length?next.map(sessionCard).join(''):'<div class="empty">Nenhuma sessão pendente. Que conquista!</div>';renderPlan();renderCourses();fillCourseOptions();bindChecks()}
function renderPlan(){const track=$('#trackFilter').value||'all',status=$('#statusFilter').value||'all';const list=state.sessions.filter(s=>(track==='all'||s.courseId===track)&&(status==='all'||(status==='done'&&s.done)||(status==='pending'&&!s.done))).sort((a,b)=>a.date.localeCompare(b.date));let month='';$('#allSessions').innerHTML=list.map(s=>{const m=localDate(s.date).toLocaleDateString('pt-BR',{month:'long',year:'numeric'});const head=m!==month?`<div class="timeline-month">${month=m}</div>`:'';return head+sessionCard(s)}).join('')||'<div class="empty">Nenhuma sessão encontrada.</div>';bindChecks()}
function renderCourses(){$('#courseGrid').innerHTML=state.courses.map(c=>{const ss=state.sessions.filter(s=>s.courseId===c.id),done=ss.filter(s=>s.done).length,p=ss.length?Math.round(done/ss.length*100):0;return `<article class="course-card" style="--course-color:${c.color}"><h3>${escapeHtml(c.name)}</h3><p class="meta">${ss.length} sessões • ${fmtMinutes(ss.reduce((a,s)=>a+s.minutes,0))}</p><div class="course-progress"><span style="width:${p}%"></span></div><footer><span>${done} concluídas</span><strong>${p}%</strong></footer></article>`}).join('')||'<div class="empty">Adicione seu primeiro curso.</div>'}
function fillCourseOptions(){const opts=state.courses.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('');$('#sessionCourse').innerHTML=opts;const current=$('#trackFilter').value;$('#trackFilter').innerHTML='<option value="all">Todos os cursos</option>'+opts;if([...$('#trackFilter').options].some(o=>o.value===current))$('#trackFilter').value=current}
function bindChecks(){$$('.check').forEach(el=>el.onchange=()=>{const s=state.sessions.find(x=>x.id===el.dataset.sessionId);s.done=el.checked;s.completedAt=el.checked?new Date().toISOString():null;save();toast(el.checked?'Sessão concluída!':'Sessão reaberta')})}
function calcStreak(){const days=[...new Set(state.sessions.filter(s=>s.done&&s.completedAt).map(s=>s.completedAt.slice(0,10)))].sort().reverse();if(!days.length)return 0;let streak=1;for(let i=1;i<days.length;i++){const a=localDate(days[i-1]),b=localDate(days[i]);if((a-b)/86400000===1)streak++;else break}return streak}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.view}View`).classList.add('active')});
$$('[data-open-modal]').forEach(b=>b.onclick=()=>{$(`#${b.dataset.openModal}Modal`).showModal()});$$('.close-modal').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#sessionForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.sessions.push({id:`s${Date.now()}`,date:f.get('date'),courseId:f.get('course'),module:f.get('module'),title:f.get('title'),minutes:Number(f.get('minutes')),done:false,completedAt:null});save();e.target.reset();$('#sessionModal').close();toast('Sessão adicionada')};
$('#courseForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),name=f.get('name');state.courses.push({id:`c${Date.now()}`,name,color:f.get('color')});save();e.target.reset();$('#courseModal').close();toast('Curso criado')};
$('#trackFilter').onchange=renderPlan;$('#statusFilter').onchange=renderPlan;$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save()};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`plano-estudos-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!data.courses||!data.sessions)throw 0;state=data;save();toast('Backup restaurado')}catch{toast('Arquivo de backup inválido')}};
$('#resetBtn').onclick=()=>{if(confirm('Restaurar o plano inicial e apagar alterações?')){state=structuredClone(initialState);save();toast('Plano restaurado')}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').hidden=true}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
render();
