const STORAGE_KEY='plano-estudos-v1';
const initialCourses=[
  {id:'fiap',name:'Big Data to Analytics',color:'#ed1c24',platform:'fiap',order:1},
  {id:'challenge',name:'Tech Challenge',color:'#f05a62',platform:'fiap',order:2},
  {id:'python',name:'Formação em Python',color:'#20639b',platform:'etek',order:1,status:'current'},
  {id:'ia',name:'Trilha de Inteligência Artificial',color:'#7c5ce5',platform:'etek',order:2,status:'planned'},
  {id:'powerbi',name:'Trilha de Power BI',color:'#f6a623',platform:'etek',order:3,status:'planned'},
  {id:'automacao',name:'Trilha de Automação',color:'#3caea3',platform:'etek',order:4,status:'planned'}
];
const rows=[
['2026-07-13','python','Preparação','Instalação do Python, VS Code e primeiros códigos',60],['2026-07-14','python','Fundamentos','Print, variáveis e operadores',60],['2026-07-15','python','Fundamentos','Strings, input e formatação',60],['2026-07-16','python','Estruturas','Listas, tuplas e dicionários',60],['2026-07-17','python','Lógica','If, for e while',60],['2026-07-18','python','Prática','Exercício de revisão dos fundamentos',60],
['2026-07-20','fiap','Big Data','Aula 1 — Definição e os 5 Vs do Big Data',90],['2026-07-21','python','Fundamentos','Operadores relacionais, lógicos e de associação',60],['2026-07-22','fiap','Big Data','Aula 2 — Hadoop e Spark',90],['2026-07-23','python','Fundamentos','Escopo de variáveis e range',60],['2026-07-25','challenge','Revisão','Revisar Big Data e praticar estruturas',120],['2026-07-27','fiap','Big Data','Aula 3 — Armazenamento de dados na nuvem',90],['2026-07-28','python','Estruturas','Listas — exercícios práticos',60],['2026-07-29','fiap','Big Data','Aula 4 — Manipulação de dados com Spark',90],['2026-07-30','python','Estruturas','Tuplas e dicionários — prática',60],['2026-08-01','challenge','Planejamento','Registrar ideias e dúvidas do projeto',120],
['2026-08-03','fiap','Bancos de Dados','Aula 1 — Bancos relacionais',90],['2026-08-04','python','Lógica','Estruturas de decisão if',60],['2026-08-05','fiap','Bancos de Dados','Aula 2 — Modelo Entidade-Relacionamento',90],['2026-08-06','python','Lógica','Laços for e while',60],['2026-08-08','challenge','Pesquisa','Relacionar o conteúdo ao desafio',120],['2026-08-10','fiap','Bancos de Dados','Aula 3 — DW, Data Lake, Lakehouse, Mesh e Fabric',90],['2026-08-11','python','Qualidade','Tratamento de erros',60],['2026-08-12','fiap','Bancos de Dados','Aula 4 — SQL, filtros, agrupamentos e joins',90],['2026-08-13','python','Bibliotecas','Math, random e time',60],['2026-08-15','challenge','Escopo','Definir tema, dados e entregáveis',120],['2026-08-17','fiap','Bancos de Dados','Aula 5 — Bancos NoSQL',90],['2026-08-18','python','Bibliotecas','Datetime e os',60],['2026-08-19','fiap','Storage','Aula 1 — Data Warehouse',90],['2026-08-20','python','Dados sintéticos','Faker e num2words',60],['2026-08-22','challenge','Arquitetura','Desenhar a solução e dividir tarefas',120],
['2026-08-24','fiap','Storage','Aula 2 — Data Lake',90],['2026-08-25','python','NumPy','NumPy — aulas 1 e 2',60],['2026-08-26','fiap','Storage','Aula 3 — Data Lakehouse',90],['2026-08-27','python','NumPy e Pandas','NumPy 3 e introdução ao Pandas',60],['2026-08-29','challenge','Implementação','Começar scripts e documentação',120],['2026-08-31','fiap','Revisão','Revisar Big Data e bancos de dados',90],['2026-09-01','python','Pandas','Pandas — aulas 1 a 4',60],['2026-09-02','fiap','Revisão','Revisar storage, Spark e Databricks',90],['2026-09-03','python','Pandas','Pandas — aulas 5 a 8',60],['2026-09-05','challenge','Implementação','Desenvolver e testar a solução',120],['2026-09-07','fiap','Revisão final','Consolidar conceitos e pendências',90],['2026-09-08','python','Pandas','Pandas — aulas 9 a 11',60],['2026-09-09','challenge','Finalização','Fechar documentação e apresentação',90],['2026-09-10','python','Visualização','Matplotlib e finalização do curso',60],['2026-09-12','challenge','Revisão final','Revisar e deixar pronto para envio',120],['2026-09-14','challenge','Entrega','Conferência final e envio — prazo oficial 15/09',30]
];
const initialState={courses:initialCourses,sessions:rows.map((r,i)=>({id:`s${i+1}`,date:r[0],courseId:r[1],module:r[2],title:r[3],minutes:r[4],done:false,completedAt:null})),theme:'light'};
const pythonLessonMap={
  'Instalação do Python, VS Code e primeiros códigos':['Instalar o Python','Configurar o VS Code','Rodar os primeiros códigos'],
  'Print, variáveis e operadores':['Print','Variáveis','Operadores'],
  'Strings, input e formatação':['Strings','Input de dados','Formatação de textos'],
  'Listas, tuplas e dicionários':['Listas','Tuplas','Dicionários'],
  'If, for e while':['Condições com if','Repetições com for','Repetições com while'],
  'Exercício de revisão dos fundamentos':['Revisão dos fundamentos','Exercícios práticos'],
  'Operadores relacionais, lógicos e de associação':['Operadores relacionais','Operadores lógicos','Operadores de associação'],
  'Escopo de variáveis e range':['Escopo de variáveis','Função range'],
  'Listas — exercícios práticos':['Exercícios de listas','Desafio prático de listas'],
  'Tuplas e dicionários — prática':['Prática com tuplas','Prática com dicionários'],
  'Estruturas de decisão if':['If e else','Elif e condições combinadas'],
  'Laços for e while':['Laço for','Laço while'],
  'Tratamento de erros':['Try e except','Tratamento de exceções'],
  'Math, random e time':['Biblioteca math','Biblioteca random','Biblioteca time'],
  'Datetime e os':['Biblioteca datetime','Biblioteca os'],
  'Faker e num2words':['Faker','Num2words'],
  'NumPy — aulas 1 e 2':['NumPy — aula 1','NumPy — aula 2'],
  'NumPy 3 e introdução ao Pandas':['NumPy — aula 3','Introdução ao Pandas'],
  'Pandas — aulas 1 a 4':['Pandas — aula 1','Pandas — aula 2','Pandas — aula 3','Pandas — aula 4'],
  'Pandas — aulas 5 a 8':['Pandas — aula 5','Pandas — aula 6','Pandas — aula 7','Pandas — aula 8'],
  'Pandas — aulas 9 a 11':['Pandas — aula 9','Pandas — aula 10','Pandas — aula 11'],
  'Matplotlib e finalização do curso':['Matplotlib','Finalização do curso']
};
let state=loadState();let installPrompt=null;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function loadState(){try{return migrateState(JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(initialState))}catch{return migrateState(structuredClone(initialState))}}
function migrateState(saved){saved.courses=saved.courses||[];initialCourses.forEach(base=>{const found=saved.courses.find(c=>c.id===base.id);if(found)Object.assign(found,base);else saved.courses.push({...base})});saved.sessions=saved.sessions||[];saved.theme=saved.theme||'light';moveWeekends(saved.sessions);return saved}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}
function course(id){return state.courses.find(c=>c.id===id)||{name:'Outro',color:'#7c5ce5'}}
function fmtMinutes(m){const h=Math.floor(m/60),min=m%60;return h?`${h}h${min?` ${min}min`:''}`:`${min}min`}
function localDate(s){return new Date(`${s}T12:00:00`)}
function isoDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function nextWeekday(date){const d=localDate(date);while([0,6].includes(d.getDay()))d.setDate(d.getDate()+1);return isoDate(d)}
function moveWeekends(sessions){let moved=0;sessions.filter(s=>!s.done).forEach(s=>{const safe=nextWeekday(s.date);if(safe!==s.date){s.date=safe;moved++}});return moved}
function priority(s){return course(s.courseId).platform==='fiap'?0:1}
function byPriority(a,b){return a.date.localeCompare(b.date)||priority(a)-priority(b)||a.title.localeCompare(b.title)}
function parseDuration(value){const text=String(value).trim();if(/^\d+$/.test(text))return Number(text);if(/^\d{1,3}:\d{2}$/.test(text)){const [m,s]=text.split(':').map(Number);if(s<60)return Math.max(1,Math.ceil((m*60+s)/60))}return 0}
function dateParts(s){const d=localDate(s);return{day:d.getDate(),month:d.toLocaleDateString('pt-BR',{month:'short'}).replace('.',''),full:d.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}}
function sessionLessons(s){return s.courseId==='python'?(pythonLessonMap[s.title]||[s.title]):[]}
function lessonList(s){const lessons=sessionLessons(s);return lessons.length?`<ol class="lesson-list">${lessons.map((lesson,i)=>`<li><span>Aula ${i+1}</span>${escapeHtml(lesson)}</li>`).join('')}</ol>`:''}
function sessionCard(s){const c=course(s.courseId),d=dateParts(s.date),fiap=c.platform==='fiap',lessons=sessionLessons(s);return `<article class="session-card ${s.done?'done':''} ${fiap?'fiap-priority':''}" style="--course-color:${c.color}"><div class="date-box"><strong>${d.day}</strong><span>${d.month}</span></div><div><h3>${escapeHtml(s.title)} ${fiap?'<span class="priority-tag">PRIORIDADE</span>':''}</h3><div class="meta"><span class="pill">${escapeHtml(c.name)}</span><span>${escapeHtml(s.module)}</span><span>${lessons.length?`${lessons.length} ${lessons.length===1?'aula':'aulas'} • `:''}${fmtMinutes(s.minutes)}</span>${s.actualMinutes?`<span>Realizado: ${fmtMinutes(s.actualMinutes)}</span>`:''}</div>${lessonList(s)}</div><input class="check" type="checkbox" aria-label="Marcar ${escapeHtml(s.title)} como concluído" data-session-id="${s.id}" ${s.done?'checked':''}></article>`}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function render(){document.documentElement.classList.toggle('dark',state.theme==='dark');$('#themeBtn').textContent=state.theme==='dark'?'☀':'☾';const total=state.sessions.reduce((a,s)=>a+s.minutes,0),done=state.sessions.filter(s=>s.done).reduce((a,s)=>a+s.minutes,0),pct=total?Math.round(done/total*100):0;$('#totalHours').textContent=fmtMinutes(total);$('#doneHours').textContent=fmtMinutes(done);$('#remainingCount').textContent=state.sessions.filter(s=>!s.done).length;$('#progressPercent').textContent=`${pct}%`;$('#progressRing').style.strokeDashoffset=308-(308*pct/100);$('#streak').textContent=`${calcStreak()} dias úteis`;const now=new Date();$('#todayLabel').textContent=now.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});$('#weekendNotice').hidden=![0,6].includes(now.getDay());const next=state.sessions.filter(s=>!s.done).sort(byPriority).slice(0,5);$('#heroTitle').textContent=next[0]?`Próximo: ${next[0].title}`:'Plano concluído!';$('#heroSubtitle').textContent=next[0]?`${dateParts(next[0].date).full} • ${fmtMinutes(next[0].minutes)}`:'Você concluiu todas as sessões.';$('#nextSessions').innerHTML=next.length?next.map(sessionCard).join(''):'<div class="empty">Nenhuma sessão pendente. Que conquista!</div>';renderTodayOverview(now);renderPlan();renderCourses();fillCourseOptions();fillStudyOptions();bindChecks()}
function renderTodayOverview(now){const today=isoDate(now),sessions=state.sessions.filter(s=>!s.done&&s.date===today).sort(byPriority),minutes=sessions.reduce((a,s)=>a+s.minutes,0),activities=sessions.reduce((n,s)=>n+(sessionLessons(s).length||1),0),weekend=[0,6].includes(now.getDay());$('#todayPlan').textContent=weekend?'Descanso':activities?`${activities} ${activities===1?'aula':'aulas'}`:'Agenda livre';$('#todayDetail').textContent=weekend?'Sábado e domingo são seus':sessions.length?sessions.map(s=>course(s.courseId).name).filter((v,i,a)=>a.indexOf(v)===i).join(' + '):'Nenhum estudo pendente para hoje';$('#todayMinutes').textContent=fmtMinutes(minutes);if(minutes){const finish=new Date(now.getTime()+minutes*60000);$('#finishTime').textContent=finish.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});$('#finishDetail').textContent=`considerando início às ${now.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`}else{$('#finishTime').textContent='—';$('#finishDetail').textContent=weekend?'Aproveite seu descanso':'Sem estudos pendentes'}const fiap=sessions.find(s=>course(s.courseId).platform==='fiap');$('#todayFocus').textContent=fiap?'FIAP':sessions.length?course(sessions[0].courseId).name:'FIAP'}
function renderPlan(){const track=$('#trackFilter').value||'all',status=$('#statusFilter').value||'all';const list=state.sessions.filter(s=>(track==='all'||s.courseId===track)&&(status==='all'||(status==='done'&&s.done)||(status==='pending'&&!s.done))).sort(byPriority);let month='';$('#allSessions').innerHTML=list.map(s=>{const m=localDate(s.date).toLocaleDateString('pt-BR',{month:'long',year:'numeric'});const head=m!==month?`<div class="timeline-month">${month=m}</div>`:'';return head+sessionCard(s)}).join('')||'<div class="empty">Nenhuma sessão encontrada.</div>';bindChecks()}
function courseMetrics(c){const ss=state.sessions.filter(s=>s.courseId===c.id),done=ss.filter(s=>s.done).length,p=ss.length?Math.round(done/ss.length*100):0;return{ss,done,p,minutes:ss.reduce((a,s)=>a+s.minutes,0)}}
function compactCourse(c){const m=courseMetrics(c);return `<article class="mini-course" style="--course-color:${c.color}"><div><span class="mini-dot"></span><h4>${escapeHtml(c.name)}</h4><p>${m.ss.length} sessões • ${fmtMinutes(m.minutes)}</p></div><strong>${m.p}%</strong><div class="mini-progress"><span style="width:${m.p}%"></span></div></article>`}
function pythonGuide(){const upcoming=state.sessions.filter(s=>s.courseId==='python'&&!s.done).sort(byPriority).slice(0,4);if(!upcoming.length)return '<div class="python-guide complete-guide"><strong>Python concluído!</strong><span>Você terminou todas as aulas planejadas.</span></div>';return `<div class="python-guide"><div class="guide-title"><strong>Suas próximas aulas</strong><span>Faça na ordem abaixo</span></div>${upcoming.map(s=>{const d=dateParts(s.date),lessons=sessionLessons(s);return `<div class="python-day"><div class="python-day-date"><strong>${d.full}</strong><span>${lessons.length} ${lessons.length===1?'aula':'aulas'} • ${fmtMinutes(s.minutes)}</span></div><ol>${lessons.map((lesson,i)=>`<li><b>${i+1}</b>${escapeHtml(lesson)}</li>`).join('')}</ol></div>`}).join('')}<div class="weekend-free">☕ Sábado e domingo livres</div></div>`}
function renderCourses(){
  const fiap=state.courses.filter(c=>c.platform==='fiap').sort((a,b)=>a.order-b.order);
  $('#fiapCourses').innerHTML=fiap.map(compactCourse).join('');
  const etek=state.courses.filter(c=>c.platform==='etek').sort((a,b)=>a.order-b.order);
  $('#etekRoadmap').innerHTML=etek.map((c,i)=>{const m=courseMetrics(c),active=c.status==='current',complete=m.p===100&&m.ss.length>0;return `<article class="roadmap-step ${active?'active':''} ${complete?'complete':''}" style="--course-color:${c.color}"><div class="step-number">${complete?'✓':i+1}</div><div class="step-copy"><span>${active?'EM ANDAMENTO':complete?'CONCLUÍDA':'PRÓXIMA ETAPA'}</span><h4>${escapeHtml(c.name)}</h4><p>${m.ss.length?`${m.ss.length} sessões planejadas • ${m.p}% concluído`:'Será planejada quando você iniciar esta trilha.'}</p>${m.ss.length?`<div class="mini-progress"><span style="width:${m.p}%"></span></div>`:''}${c.id==='python'&&active?pythonGuide():''}</div></article>`}).join('');
  const others=state.courses.filter(c=>!c.platform||c.platform==='other');
  $('.other-courses').hidden=!others.length;
  $('#courseGrid').innerHTML=others.map(c=>{const m=courseMetrics(c);return `<article class="course-card" style="--course-color:${c.color}"><h3>${escapeHtml(c.name)}</h3><p class="meta">${m.ss.length} sessões • ${fmtMinutes(m.minutes)}</p><div class="course-progress"><span style="width:${m.p}%"></span></div><footer><span>${m.done} concluídas</span><strong>${m.p}%</strong></footer></article>`}).join('');
}
function fillCourseOptions(){const opts=state.courses.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('');$('#sessionCourse').innerHTML=opts;const current=$('#trackFilter').value;$('#trackFilter').innerHTML='<option value="all">Todos os cursos</option>'+opts;if([...$('#trackFilter').options].some(o=>o.value===current))$('#trackFilter').value=current}
function fillStudyOptions(){const pending=state.sessions.filter(s=>!s.done).sort(byPriority).slice(0,20);$('#studySession').innerHTML=pending.map(s=>`<option value="${s.id}">${escapeHtml(dateParts(s.date).full)} — ${escapeHtml(s.title)}</option>`).join('')||'<option value="">Nenhuma sessão pendente</option>'}
function bindChecks(){$$('.check').forEach(el=>el.onchange=()=>{const s=state.sessions.find(x=>x.id===el.dataset.sessionId);s.done=el.checked;s.completedAt=el.checked?new Date().toISOString():null;save();toast(el.checked?'Sessão concluída!':'Sessão reaberta')})}
function businessDaysBetween(a,b){let count=0,d=new Date(b);while(d<a){d.setDate(d.getDate()+1);if(![0,6].includes(d.getDay()))count++}return count}
function calcStreak(){const days=[...new Set(state.sessions.filter(s=>s.done&&s.completedAt).map(s=>s.completedAt.slice(0,10)))].sort().reverse();if(!days.length)return 0;let streak=1;for(let i=1;i<days.length;i++){const a=localDate(days[i-1]),b=localDate(days[i]);if(businessDaysBetween(a,b)===1)streak++;else break}return streak}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.view}View`).classList.add('active')});
$$('[data-open-modal]').forEach(b=>b.onclick=()=>{$(`#${b.dataset.openModal}Modal`).showModal()});$$('.close-modal').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#sessionForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),minutes=parseDuration(f.get('duration')),date=f.get('date');if(!minutes){toast('Informe a duração como 28:23 ou 60');return}if([0,6].includes(localDate(date).getDay())){toast('Escolha um dia útil para preservar seu descanso');return}state.sessions.push({id:`s${Date.now()}`,date,courseId:f.get('course'),module:f.get('module'),title:f.get('title'),minutes,done:false,completedAt:null});save();e.target.reset();$('#sessionModal').close();toast('Sessão adicionada em um dia útil')};
$('#studyForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),s=state.sessions.find(x=>x.id===f.get('session'));if(!s){toast('Nenhuma sessão selecionada');return}s.done=true;s.completedAt=new Date().toISOString();s.actualMinutes=Number(f.get('actualMinutes'));s.note=String(f.get('note')||'').trim();save();e.target.reset();$('#studyModal').close();toast('Estudo de hoje registrado!')};
$('#courseForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),name=f.get('name');state.courses.push({id:`c${Date.now()}`,name,color:f.get('color'),platform:'other'});save();e.target.reset();$('#courseModal').close();toast('Curso criado')};
$('#trackFilter').onchange=renderPlan;$('#statusFilter').onchange=renderPlan;$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save()};
$('#weekdayBtn').onclick=()=>{const moved=moveWeekends(state.sessions);save();toast(moved?`${moved} sessões movidas para dias úteis`:'Seu cronograma já respeita os dias úteis')};
function icsDate(date,time){return `${date.replaceAll('-','')}T${time.replace(':','')}00`}
function icsEscape(v){return String(v).replaceAll('\\','\\\\').replaceAll(',','\\,').replaceAll(';','\\;').replaceAll('\n','\\n')}
$('#calendarBtn').onclick=()=>{const pending=state.sessions.filter(s=>!s.done).sort(byPriority),lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Horizonte//Plano de Estudos//PT-BR','CALSCALE:GREGORIAN'];pending.forEach(s=>{const start='19:00',end=new Date(localDate(s.date));end.setHours(19,0,0,0);end.setMinutes(end.getMinutes()+s.minutes);const endTime=`${String(end.getHours()).padStart(2,'0')}:${String(end.getMinutes()).padStart(2,'0')}`,c=course(s.courseId),isFiap=c.platform==='fiap';lines.push('BEGIN:VEVENT',`UID:${s.id}@horizonte`, `DTSTART;TZID=America/Sao_Paulo:${icsDate(s.date,start)}`,`DTEND;TZID=America/Sao_Paulo:${icsDate(s.date,endTime)}`,`SUMMARY:${icsEscape(isFiap?'🎓 FIAP — '+s.title:'📘 '+s.title)}`,`DESCRIPTION:${icsEscape(`${c.name} • ${s.module}${isFiap?' • Prioridade FIAP':''}`)}`,'END:VEVENT')});lines.push('END:VCALENDAR');const blob=new Blob([lines.join('\r\n')],{type:'text/calendar'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='horizonte-google-agenda.ics';a.click();URL.revokeObjectURL(a.href);toast('Arquivo da agenda criado')};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`plano-estudos-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!data.courses||!data.sessions)throw 0;state=data;save();toast('Backup restaurado')}catch{toast('Arquivo de backup inválido')}};
$('#resetBtn').onclick=()=>{if(confirm('Restaurar o plano inicial e apagar alterações?')){state=structuredClone(initialState);save();toast('Plano restaurado')}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').hidden=true}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
render();
